PRAGMA foreign_keys = ON;

-- Student identity
CREATE TABLE student_profile (
    id TEXT PRIMARY KEY,          -- UUID from Supabase
    name TEXT,
    grade INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Questions asked by student
CREATE TABLE questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id TEXT NOT NULL,
    asked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    source_type TEXT,             -- photo / text
    raw_question TEXT NOT NULL,
    FOREIGN KEY (student_id) REFERENCES student_profile(id)
);

-- AI answers generated by SLM
CREATE TABLE answers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question_id INTEGER NOT NULL,
    answer_text TEXT NOT NULL,
    helpful INTEGER DEFAULT 0,
    time_taken_ms INTEGER,
    FOREIGN KEY (question_id) REFERENCES questions(id)
);

-- Quiz attempts
CREATE TABLE quizzes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id TEXT NOT NULL,
    chapter_id INTEGER,
    score INTEGER,
    taken_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES student_profile(id)
);

-- Quiz questions for each quiz
CREATE TABLE quiz_questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    quiz_id INTEGER NOT NULL,
    question TEXT NOT NULL,
    student_answer TEXT,
    correct_answer TEXT,
    is_correct INTEGER,
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id)
);

-- Chapter mastery
CREATE TABLE mastery (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id TEXT NOT NULL,
    chapter_id INTEGER NOT NULL,
    score REAL,
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES student_profile(id)
);
